### PR TITLE
fix: typed dashboard structs

### PR DESCRIPTION
**Pull request by vvv**

### CODE REVIEW

**Review by oasisk — APPROVED** [review]

**Comment by gaby** [comment]
@vvv @oasisk These changes, caused existing dashboards to disappear. It's also creating errors when visiting the dashboard page. I had to recreate my ZO instance from scratch to fix it.

**Comment by hengfeiyang** [comment]
@gaby Yes, you are right, we will try to make it happen earlier. we wrote some notices in the release note:
https://github.com/zinclabs/zincobserve/releases/tag/v0.3.2

**Comment by gaby** [comment]
@hengfeiyang No worries, I completely skipped reading the release notes. Thanks for that :-)

**Comment by vvv** [comment]
> @vvv @oasisk These changes, caused existing dashboards to disappear. It's also creating errors when visiting the dashboard page. I had to recreate my ZO instance from scratch to fix it.

@gaby Ouch.  I do beg your pardon. 😞 And there is yet [another breaking change](https://github.com/zinclabs/zincobserve/pull/503) heading your way...

#466 and #503 are the pieces enabling ‘Dashboards export/import’ functionality (#438). The end of suffering is nigh.

**Comment by gaby** [comment]
@vvv Thanks for the headsup. I'm mostly testing ZO, so no worries. Already have over 500M events stored in an instance.

**Pull request merged**
